# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEquipmentLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Log de Equipamento da Atividade',
                'verbose_name_plural': 'Logs de Equipamento da Atividade',
                'db_table': 'A_EQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityNonConformanceLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('quantity', models.DecimalField(blank=True, db_column='QUANTIDADE', decimal_places=10, max_digits=20, null=True, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Log de Não Conformidade da Atividade',
                'verbose_name_plural': 'Logs de Não Conformidade da Atividade',
                'db_table': 'A_NAOCONFORMIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityWorkforceLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Log de Mão de Obra da Atividade',
                'verbose_name_plural': 'Logs de Mão de Obra da Atividade',
                'db_table': 'A_MAOOBRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentStoppageLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Log de Parada de Equipamento',
                'verbose_name_plural': 'Logs de Parada de Equipamento',
                'db_table': 'A_PARADA_EQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderActivityProgress',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('sequence', models.IntegerField(db_column='SEQUENCIA', verbose_name='Sequência')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Data de Fim')),
                ('quantity', models.DecimalField(blank=True, db_column='QUANTIDADE', decimal_places=2, max_digits=20, null=True, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Parado', 'Parado'), ('Finalizado', 'Finalizado')], default='Em Andamento', max_length=20, verbose_name='Status do Apontamento')),
            ],
            options={
                'verbose_name': 'Atividade da Ordem',
                'verbose_name_plural': 'Atividades da Ordem',
                'db_table': 'A_ATIVIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceStoppageLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Log de Parada de Mão de Obra',
                'verbose_name_plural': 'Logs de Parada de Mão de Obra',
                'db_table': 'A_PARADA_MAOOBRA',
                'managed': False,
            },
        ),
    ]
