# Generated by Django 5.0.14 on 2025-06-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderactivityprogress',
            options={'managed': True, 'verbose_name': 'Atividade da Ordem', 'verbose_name_plural': 'Atividades da Ordem'},
        ),
    ]
