# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(blank=True, db_column='NOME', max_length=150, null=True, verbose_name='Nome')),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=150, null=True, verbose_name='E-mail')),
                ('rg', models.CharField(blank=True, db_column='RG', max_length=15, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=20, null=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, db_column='TELEFONE', max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, db_column='ENDERECO', max_length=100, null=True, verbose_name='Endereço')),
                ('city_code_fk', models.IntegerField(blank=True, db_column='CODCIDADE', null=True, verbose_name='Código da Cidade (Ref)')),
                ('user_profile_code', models.IntegerField(blank=True, db_column='CODPERFILUSUARIO', null=True, verbose_name='Código do Perfil de Usuário')),
                ('username', models.CharField(blank=True, db_column='USUARIO', max_length=50, null=True, verbose_name='Usuário (Login)')),
                ('password', models.CharField(blank=True, db_column='SENHA', max_length=20, null=True, verbose_name='Senha')),
                ('sector_code', models.IntegerField(blank=True, db_column='CODSETOR', null=True, verbose_name='Código do Setor')),
                ('uc_login', models.CharField(blank=True, db_column='UCLOGIN', max_length=30, null=True, verbose_name='UC Login')),
                ('uc_password', models.CharField(blank=True, db_column='UCPASSWORD', max_length=250, null=True, verbose_name='UC Senha')),
                ('uc_password_expired_flag', models.CharField(blank=True, db_column='UCPASSEXPIRED', max_length=10, null=True, verbose_name='UC Senha Expirada (Flag)')),
                ('uc_user_expired_flag', models.IntegerField(blank=True, db_column='UCUSEREXPIRED', null=True, verbose_name='UC Usuário Expirado (Flag)')),
                ('uc_user_days_sun', models.IntegerField(blank=True, db_column='UCUSERDAYSSUN', null=True, verbose_name='UC Dias Usuário Sol')),
                ('uc_is_privileged', models.IntegerField(blank=True, db_column='UCPRIVILEGED', null=True, verbose_name='UC Privilegiado')),
                ('uc_type_rec', models.CharField(blank=True, db_column='UCTYPEREC', max_length=1, null=True, verbose_name='UC Tipo Rec.')),
                ('uc_profile_code', models.IntegerField(blank=True, db_column='UCPROFILE', null=True, verbose_name='UC Código do Perfil')),
                ('uc_key', models.CharField(blank=True, db_column='UCKEY', max_length=250, null=True, verbose_name='UC Chave')),
                ('uc_email', models.CharField(blank=True, db_column='UCEMAIL', max_length=150, null=True, verbose_name='UC E-mail')),
                ('uc_user_id', models.IntegerField(blank=True, db_column='UCIDUSER', null=True, verbose_name='UC ID Usuário')),
                ('uc_username', models.CharField(blank=True, db_column='UCUSERNAME', max_length=30, null=True, verbose_name='UC Nome de Usuário')),
                ('customer_supplier_fk', models.IntegerField(blank=True, db_column='CODIGO_CLIFORN', null=True, verbose_name='Cliente/Fornecedor')),
                ('uc_is_inactive', models.IntegerField(blank=True, db_column='UCINATIVE', null=True, verbose_name='UC Inativo')),
                ('allows_release_movements', models.IntegerField(blank=True, db_column='PERMITE_LIBERAR_MOVIMENTOS', null=True, verbose_name='Permite Liberar Movimentos')),
                ('sat_dll_path', models.CharField(blank=True, db_column='CAMINHO_DLL_SAT', max_length=500, null=True, verbose_name='Caminho DLL SAT')),
                ('sat_cashier_number', models.CharField(blank=True, db_column='NUMERO_CAIXA_SAT', max_length=10, null=True, verbose_name='Número Caixa SAT')),
                ('email_smtp_server', models.CharField(blank=True, db_column='EMAIL_SERVIDOR_SMTP', max_length=100, null=True, verbose_name='E-mail Servidor SMTP')),
                ('email_smtp_port', models.CharField(blank=True, db_column='EMAIL_PORTA_SMTP', max_length=50, null=True, verbose_name='E-mail Porta SMTP')),
                ('email_user', models.CharField(blank=True, db_column='EMAIL_USUARIO', max_length=100, null=True, verbose_name='E-mail Usuário')),
                ('email_password', models.CharField(blank=True, db_column='EMAIL_SENHA', max_length=50, null=True, verbose_name='E-mail Senha')),
                ('email_default_subject', models.CharField(blank=True, db_column='EMAIL_ASSUNTO_PADRAO', max_length=100, null=True, verbose_name='E-mail Assunto Padrão')),
                ('email_default_message', models.CharField(blank=True, db_column='EMAIL_MENSAGEM_PADRAO', max_length=1000, null=True, verbose_name='E-mail Mensagem Padrão')),
                ('email_uses_authentication', models.IntegerField(blank=True, db_column='EMAIL_UTILIZA_AUTENTICACAO', null=True, verbose_name='E-mail Utiliza Autenticação')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'COLABORADOR',
                'managed': False,
            },
        ),
    ]
