# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('order_id', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem')),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=30, null=True, verbose_name='Status da Ordem')),
                ('opening_date', models.DateTimeField(blank=True, db_column='DATAABERTURA', null=True, verbose_name='Data de Abertura')),
                ('closing_date', models.DateTimeField(blank=True, db_column='DATATERMINO', null=True, verbose_name='Data de Término')),
                ('necessity_origin', models.IntegerField(blank=True, db_column='ORIGEMNECESSIDADE', null=True, verbose_name='Origem da Necessidade')),
                ('programming_type', models.IntegerField(blank=True, db_column='TIPOPROGRAMACAO', null=True, verbose_name='Tipo de Programação')),
                ('order_description', models.CharField(blank=True, db_column='DESCORDEM', max_length=200, null=True, verbose_name='Descrição da Ordem')),
                ('responsible', models.CharField(blank=True, db_column='RESPONSAVEL', max_length=200, null=True, verbose_name='Responsável')),
                ('order_type', models.IntegerField(blank=True, db_column='TIPOORDEM', null=True, verbose_name='Tipo de Ordem')),
                ('order_observation', models.TextField(blank=True, db_column='OBSORDEM', null=True, verbose_name='Observação da Ordem')),
                ('exp_mobile', models.CharField(blank=True, db_column='EXPMOBILE', max_length=3, null=True, verbose_name='Exp. Mobile')),
                ('order_cost', models.DecimalField(blank=True, db_column='CUSTOORDEM', decimal_places=8, max_digits=18, null=True, verbose_name='Custo da Ordem')),
                ('posted_quantity', models.DecimalField(blank=True, db_column='QTDEAPONTADA', decimal_places=8, max_digits=18, null=True, verbose_name='Quantidade Apontada')),
                ('planned_quantity', models.DecimalField(blank=True, db_column='QTDEPREVISTA', decimal_places=8, max_digits=18, null=True, verbose_name='Quantidade Prevista')),
                ('proportionality', models.DecimalField(db_column='PROPORCIONALIDADE', decimal_places=10, max_digits=20, verbose_name='Proporcionalidade')),
                ('planning_code', models.IntegerField(blank=True, db_column='CODIGO_PLANEJAMENTO', null=True, verbose_name='Código do Planejamento')),
                ('mrp_necessity_code', models.IntegerField(blank=True, db_column='CODIGO_NECESSIDADEMRP', null=True, verbose_name='Código da Necessidade MRP')),
                ('order_printed', models.CharField(blank=True, db_column='ORDEMIMPRESSA', max_length=3, null=True, verbose_name='Ordem Impressa')),
                ('last_recalculation_date', models.DateTimeField(blank=True, db_column='DATA_ULTIMO_RECALCULO', null=True, verbose_name='Data do Último Recálculo')),
                ('new_item_code', models.CharField(blank=True, db_column='CODITEMNOVO', max_length=100, null=True, verbose_name='Código do Item Novo')),
                ('brand', models.CharField(blank=True, db_column='MARCA', max_length=100, null=True, verbose_name='Marca')),
                ('department', models.CharField(blank=True, db_column='DEPARTAMENTO', max_length=100, null=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Ordem',
                'verbose_name_plural': 'Ordens',
                'db_table': 'F_ORDEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('mrp_necessity', models.IntegerField(blank=True, db_column='CODNECESSIDADE', null=True, verbose_name='Necessidade MRP')),
                ('order_id_fk', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem (Texto)')),
                ('necessity_date', models.DateTimeField(blank=True, db_column='DTNECESSIDADE', null=True, verbose_name='Data da Necessidade')),
                ('planned_quantity', models.DecimalField(blank=True, db_column='QUANTIDADEPREVISTA', decimal_places=10, max_digits=20, null=True, verbose_name='Quantidade Prevista')),
                ('completed_quantity', models.DecimalField(blank=True, db_column='QUANTIDADEREALIZADA', decimal_places=10, max_digits=20, null=True, verbose_name='Quantidade Realizada')),
            ],
            options={
                'verbose_name': 'Item da Ordem',
                'verbose_name_plural': 'Itens da Ordem',
                'db_table': 'F_ITEMORDEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPlannedMaterial',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('order_id_text', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem (Texto)')),
                ('raw_material_id_text', models.CharField(blank=True, db_column='IDMATPRIMA', max_length=30, null=True, verbose_name='ID da Matéria Prima (Texto)')),
                ('raw_material_description', models.CharField(blank=True, db_column='DESCMATERIAPRIMA', max_length=200, null=True, verbose_name='Descrição da Matéria Prima')),
                ('quantity', models.DecimalField(blank=True, db_column='QUANTIDADE', decimal_places=8, max_digits=18, null=True, verbose_name='Quantidade')),
                ('necessity_start_date', models.DateTimeField(blank=True, db_column='DATAINICIONECESSIDADE', null=True, verbose_name='Data de Início da Necessidade')),
                ('planned_cost', models.DecimalField(blank=True, db_column='CUSTOPREVISTO', decimal_places=8, max_digits=18, null=True, verbose_name='Custo Previsto')),
                ('stock_location_code', models.IntegerField(blank=True, db_column='CODLOCALESTOQUE', null=True, verbose_name='Código do Local de Estoque')),
                ('sequence', models.IntegerField(blank=True, db_column='SEQUENCIA', null=True, verbose_name='Sequência')),
                ('origin', models.IntegerField(blank=True, db_column='ORIGEM', null=True, verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Material Previsto da Ordem',
                'verbose_name_plural': 'Materiais Previstos da Ordem',
                'db_table': 'F_MATERIALPREVISTOORDEM',
                'managed': False,
            },
        ),
    ]
