# Generated by Django 5.0.14 on 2025-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('order_id_text', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem (Texto)')),
                ('parent_order_id', models.CharField(blank=True, db_column='ORDEM_PAI', max_length=20, null=True, verbose_name='Ordem Pai')),
                ('sequence', models.IntegerField(blank=True, db_column='SEQUENCIA', null=True, verbose_name='Sequência')),
                ('start_date', models.DateTimeField(blank=True, db_column='INICIOEFETIVO', null=True, verbose_name='Início Efetivo')),
                ('end_date', models.DateTimeField(blank=True, db_column='FIMEFETIVO', null=True, verbose_name='Fim Efetivo')),
                ('pointed_quantity', models.DecimalField(blank=True, db_column='QTDEAPONTADA', decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade Apontada')),
                ('effective_cost', models.DecimalField(blank=True, db_column='CUSTOEFETIVO', decimal_places=8, max_digits=18, null=True, verbose_name='Custo Efetivo')),
                ('integration_status', models.CharField(blank=True, db_column='STATUSINTEGRACAO', max_length=20, null=True, verbose_name='Status de Integração')),
                ('material_status', models.CharField(blank=True, db_column='STATUSMP', max_length=10, null=True, verbose_name='Status Matéria-Prima')),
                ('created_at', models.DateTimeField(blank=True, db_column='DTCRIACAO', null=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Apontamento de Atividade',
                'verbose_name_plural': 'Apontamentos de Atividade',
                'db_table': 'F_APONTAMENTOATIVIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentAppointmentLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código do Log')),
                ('order_id_text', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem (Texto)')),
                ('start_date', models.DateTimeField(blank=True, db_column='INICIOEFETIVO', null=True, verbose_name='Início Efetivo')),
                ('end_date', models.DateTimeField(blank=True, db_column='FIMEFETIVO', null=True, verbose_name='Fim Efetivo')),
                ('pointed_quantity', models.DecimalField(blank=True, db_column='QTDEAPONTADA', decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade Apontada')),
                ('effective_cost', models.DecimalField(blank=True, db_column='CUSTOEFETIVO', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Efetivo')),
                ('created_at', models.DateTimeField(blank=True, db_column='DTCRIACAO', null=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Log de Apontamento de Equipamento',
                'verbose_name_plural': 'Logs de Apontamento de Equipamento',
                'db_table': 'F_APONTAMENTOEQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoppageAppointmentEquipmentLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código do Log de Parada')),
                ('start_date', models.DateTimeField(blank=True, db_column='INICIOPARADA', null=True, verbose_name='Início da Parada')),
                ('end_date', models.DateTimeField(blank=True, db_column='FIMPARADA', null=True, verbose_name='Fim da Parada')),
                ('created_at', models.DateTimeField(blank=True, db_column='DTCRIACAO', null=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Log de Apontamento de Parada',
                'verbose_name_plural': 'Logs de Apontamento de Parada',
                'db_table': 'F_APONTAMENTOPARADAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoppageAppointmentWorkforceLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código do Log de Parada')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATA_INICIO', null=True, verbose_name='Início da Parada')),
                ('end_date', models.DateTimeField(blank=True, db_column='DATA_FIM', null=True, verbose_name='Fim da Parada')),
                ('created_at', models.DateTimeField(blank=True, db_column='DTCRIACAO', null=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Log de Parada de Mão de Obra',
                'verbose_name_plural': 'Logs de Parada de Mão de Obra',
                'db_table': 'F_APONTAMENTOPARADAS_MAOOBRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceAppointmentLog',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código do Log')),
                ('order_id_text', models.CharField(blank=True, db_column='IDORDEM', max_length=100, null=True, verbose_name='ID da Ordem (Texto)')),
                ('start_date', models.DateTimeField(blank=True, db_column='INICIOEFETIVO', null=True, verbose_name='Início Efetivo')),
                ('end_date', models.DateTimeField(blank=True, db_column='FIMEFETIVO', null=True, verbose_name='Fim Efetivo')),
                ('effective_cost', models.DecimalField(blank=True, db_column='CUSTOEFETIVO', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Efetivo')),
                ('pointed_quantity', models.DecimalField(blank=True, db_column='QTDEAPONTADA', decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade Apontada')),
                ('branch_code', models.IntegerField(blank=True, db_column='CODFILIAL', null=True, verbose_name='Código da Filial')),
                ('created_at', models.DateTimeField(blank=True, db_column='DTCRIACAO', null=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Log de Apontamento de Mão de Obra',
                'verbose_name_plural': 'Logs de Apontamento de Mão de Obra',
                'db_table': 'F_APONTAMENTOMOBRA',
                'managed': False,
            },
        ),
    ]
