# Generated by Django 5.0.14 on 2025-06-18 14:35

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome / Título do Arquivo')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('PDF', 'PDF'), ('TECHNICAL_DRAWING', 'Desenho Técnico'), ('STL', 'Modelo 3D (.stl)')], max_length=20, verbose_name='Tipo de Arquivo')),
                ('file', models.FileField(upload_to=products.models.get_product_file_path, verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('activity', models.ForeignKey(blank=True, help_text='Deixe este campo em branco se o arquivo for para TODAS as atividades do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activitys.activity', verbose_name='Atividade Específica (Opcional)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Arquivo de Produto',
                'verbose_name_plural': 'Arquivos de Produto',
                'ordering': ['file_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('product', models.ForeignKey(db_column='CODPRODUTO', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Produto')),
            ],
        ),
    ]
