# Generated by Django 5.0.14 on 2025-06-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productfile_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
