# Generated by Django 5.0.14 on 2025-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitys', '0001_initial'),
        ('products', '0003_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='activity',
        ),
        migrations.AddField(
            model_name='productfile',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Selecione uma ou mais atividades. Se nenhuma for selecionada, este arquivo será válido para todas as atividades do produto.', to='activitys.activity', verbose_name='Atividades Específicas'),
        ),
    ]
