# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('description', models.CharField(blank=True, db_column='DESCRICAO', max_length=30, null=True, verbose_name='Descrição')),
                ('technical_description', models.TextField(blank=True, db_column='DESCRITIVOTECNICO', null=True, verbose_name='Descritivo Técnico')),
                ('is_active', models.IntegerField(blank=True, db_column='ATIVO', null=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'F_HABILIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(blank=True, db_column='NOME', max_length=150, null=True, verbose_name='Nome')),
                ('street', models.CharField(blank=True, db_column='RUA', max_length=150, null=True, verbose_name='Rua')),
                ('street_number', models.CharField(blank=True, db_column='NUMERO', max_length=8, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, db_column='BAIRRO', max_length=150, null=True, verbose_name='Bairro')),
                ('birth_date', models.DateTimeField(blank=True, db_column='DATANASCIMENTO', null=True, verbose_name='Data de Nascimento')),
                ('rg', models.CharField(blank=True, db_column='RG', max_length=15, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=20, null=True, verbose_name='CPF')),
                ('phone1', models.CharField(blank=True, db_column='FONE', max_length=20, null=True, verbose_name='Telefone 1')),
                ('father_name', models.CharField(blank=True, db_column='NOMEPAI', max_length=80, null=True, verbose_name='Nome do Pai')),
                ('mother_name', models.CharField(blank=True, db_column='NOMEMAE', max_length=80, null=True, verbose_name='Nome da Mãe')),
                ('city_name', models.CharField(blank=True, db_column='CIDADE', max_length=60, null=True, verbose_name='Nome da Cidade')),
                ('state_uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, db_column='CEP', max_length=15, null=True, verbose_name='CEP')),
                ('phone2', models.CharField(blank=True, db_column='TELEFONE', max_length=15, null=True, verbose_name='Telefone 2')),
                ('is_active', models.IntegerField(blank=True, db_column='ATIVA', null=True, verbose_name='Ativo')),
                ('hourly_cost', models.DecimalField(blank=True, db_column='CUSTOHORAMO', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Hora M.O.')),
                ('monthly_cost', models.DecimalField(blank=True, db_column='CUSTOMESMO', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Mês M.O.')),
                ('effectiveness', models.DecimalField(blank=True, db_column='EFETIVIDADE', decimal_places=3, max_digits=6, null=True, verbose_name='Efetividade')),
                ('daily_efficiency', models.DecimalField(blank=True, db_column='EFICIENCIADIA', decimal_places=8, max_digits=18, null=True, verbose_name='Eficiência Diária')),
                ('monthly_efficiency', models.DecimalField(blank=True, db_column='EFICIENCIAMES', decimal_places=8, max_digits=18, null=True, verbose_name='Eficiência Mensal')),
                ('employee_id_plate', models.CharField(blank=True, db_column='CHAPA', max_length=10, null=True, verbose_name='Chapa (ID Funcionário)')),
                ('badge_number', models.CharField(blank=True, db_column='CRACHA', max_length=20, null=True, verbose_name='Crachá')),
                ('work_shift_minutes', models.IntegerField(blank=True, db_column='TT_TURNO_TRAB_MINUTOS', null=True, verbose_name='Total Turno de Trabalho (Minutos)')),
                ('workforce_id_text', models.CharField(blank=True, db_column='IDMAOOBRA', max_length=30, null=True, verbose_name='ID Mão de Obra (Texto)')),
                ('cost_sql', models.TextField(blank=True, db_column='SQL_CUSTO', null=True, verbose_name='SQL de Custo')),
                ('cf_sector', models.CharField(blank=True, db_column='CF_SETOR', max_length=100, null=True, verbose_name='CF Setor')),
                ('cf_situation', models.CharField(blank=True, db_column='CF_SITUACAO', max_length=300, null=True, verbose_name='CF Situação')),
            ],
            options={
                'verbose_name': 'Mão de Obra',
                'verbose_name_plural': 'Mão de Obra',
                'db_table': 'F_MAOOBRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceCostHistory',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('month', models.CharField(blank=True, db_column='MES', max_length=2, null=True, verbose_name='Mês')),
                ('year', models.CharField(blank=True, db_column='ANO', max_length=4, null=True, verbose_name='Ano')),
                ('hourly_cost', models.DecimalField(blank=True, db_column='CUSTOHORA', decimal_places=4, max_digits=10, null=True, verbose_name='Custo Hora')),
                ('monthly_cost', models.DecimalField(blank=True, db_column='CUSTOMES', decimal_places=4, max_digits=10, null=True, verbose_name='Custo Mês')),
                ('is_current', models.IntegerField(blank=True, db_column='ATUAL', null=True, verbose_name='Atual')),
            ],
            options={
                'verbose_name': 'Histórico de Custo de Mão de Obra',
                'verbose_name_plural': 'Históricos de Custo de Mão de Obra',
                'db_table': 'F_HISTCUSTOMAOOBRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceSkill',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Habilidade da Mão de Obra',
                'verbose_name_plural': 'Habilidades da Mão de Obra',
                'db_table': 'F_MAOOBRAHABILIDADES',
                'managed': False,
            },
        ),
    ]
