# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('non_conformance_id', models.CharField(blank=True, db_column='IDNAOCONFORMIDADE', max_length=30, null=True, verbose_name='ID da Não Conformidade')),
                ('description', models.CharField(blank=True, db_column='DESCRICAONCONF', max_length=200, null=True, verbose_name='Descrição da Não Conformidade')),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
                'db_table': 'F_NAOCONFORMIDADES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonConformanceWriteOffItem',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Item de Baixa de Não Conformidade',
                'verbose_name_plural': 'Itens de Baixa de Não Conformidades',
                'db_table': 'F_NCONF_ITENSBAIXA',
                'managed': False,
            },
        ),
    ]
