# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('identifier', models.CharField(db_column='IDENTIFICADOR', max_length=30, verbose_name='Identificador')),
                ('name', models.CharField(db_column='NOME', max_length=255, verbose_name='Nome do País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'G_PAIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('identifier', models.CharField(blank=True, db_column='IDENTIFICADOR', max_length=30, null=True, verbose_name='Identificador')),
                ('name', models.CharField(blank=True, db_column='NOME', max_length=255, null=True, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'G_MUNICIPIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('identifier', models.CharField(db_column='IDENTIFICADOR', max_length=30, verbose_name='Identificador')),
                ('name', models.CharField(db_column='NOME', max_length=255, verbose_name='Nome do Estado')),
                ('st_state_registration', models.CharField(blank=True, db_column='INSCRICAOESTADUAL_ST', max_length=20, null=True, verbose_name='Inscrição Estadual ST')),
                ('uses_calculation_inside', models.IntegerField(blank=True, db_column='UTILIZA_CALCULO_POR_DENTRO', null=True, verbose_name='Utiliza Cálculo por Dentro')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'G_UF',
                'managed': False,
            },
        ),
    ]
