# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('description', models.CharField(blank=True, db_column='DSCCALENDARIO', max_length=60, null=True, verbose_name='Descrição do Calendário')),
                ('year', models.CharField(blank=True, db_column='ANOCALENDARIO', max_length=4, null=True, verbose_name='Ano do Calendário')),
                ('start_date', models.DateTimeField(blank=True, db_column='DATAINICIO', null=True, verbose_name='Data de Início')),
            ],
            options={
                'verbose_name': 'Calendário de Produção',
                'verbose_name_plural': 'Calendários de Produção',
                'db_table': 'F_CALENDARIOPRODUCAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftNonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_column='DESCRICAO', max_length=50, null=True, verbose_name='Descrição')),
                ('non_working_day', models.DateTimeField(blank=True, db_column='DIASNAOUTEIS', null=True, verbose_name='Dia Não Útil')),
                ('start_time', models.CharField(blank=True, db_column='HORAINICIO', max_length=10, null=True, verbose_name='Hora de Início')),
                ('end_time', models.CharField(blank=True, db_column='HORAFIM', max_length=10, null=True, verbose_name='Hora de Fim')),
            ],
            options={
                'verbose_name': 'Turno em Dia Não Útil',
                'verbose_name_plural': 'Turnos em Dias Não Úteis',
                'db_table': 'F_TURNOSDIASNAOUTEIS',
                'managed': False,
            },
        ),
    ]
