# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeEquipment',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('company_code', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True, verbose_name='Código da Coligada')),
                ('branch_code', models.IntegerField(blank=True, db_column='CODFILIAL', null=True, verbose_name='Código da Filial')),
            ],
            options={
                'verbose_name': 'Equipamento Composto',
                'verbose_name_plural': 'Equipamentos Compostos',
                'db_table': 'F_EQUIPAMENTOCOMPOSTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('company_code', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True, verbose_name='Código da Coligada')),
                ('branch_code', models.IntegerField(blank=True, db_column='CODFILIAL', null=True, verbose_name='Código da Filial')),
                ('description', models.CharField(blank=True, db_column='DESCEQUIPAMENTO', max_length=200, null=True, verbose_name='Descrição do Equipamento')),
                ('hourly_cost', models.DecimalField(blank=True, db_column='CUSTOHORAEQP', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Hora do Equipamento')),
                ('cost_center_code', models.CharField(blank=True, db_column='CODCCUSTO', max_length=30, null=True, verbose_name='Código do Centro de Custo')),
                ('monthly_cost', models.DecimalField(blank=True, db_column='CUSTOMESEQP', decimal_places=3, max_digits=10, null=True, verbose_name='Custo Mensal do Equipamento')),
                ('effectiveness', models.DecimalField(blank=True, db_column='EFETIVIDADE', decimal_places=3, max_digits=6, null=True, verbose_name='Efetividade')),
                ('active_quantity', models.IntegerField(blank=True, db_column='QTDATIVA', null=True, verbose_name='Quantidade Ativa')),
                ('hourly_production', models.DecimalField(blank=True, db_column='PRODHORA', decimal_places=3, max_digits=10, null=True, verbose_name='Produção por Hora')),
                ('equipment_id', models.CharField(blank=True, db_column='IDEQUIPAMENTO', max_length=30, null=True, verbose_name='ID do Equipamento')),
                ('address', models.CharField(blank=True, db_column='ENDERECO', max_length=300, null=True, verbose_name='Endereço')),
                ('daily_efficiency', models.DecimalField(blank=True, db_column='EFICIENCIADIA', decimal_places=8, max_digits=18, null=True, verbose_name='Eficiência Diária')),
                ('monthly_efficiency', models.DecimalField(blank=True, db_column='EFICIENCIAMES', decimal_places=8, max_digits=18, null=True, verbose_name='Eficiência Mensal')),
                ('type', models.IntegerField(blank=True, db_column='TIPO', null=True, verbose_name='Tipo')),
                ('work_shift_minutes', models.IntegerField(blank=True, db_column='TT_TURNO_TRAB_MINUTOS', null=True, verbose_name='Total Turno de Trabalho (Minutos)')),
                ('cost_sql', models.TextField(blank=True, db_column='SQL_CUSTO', null=True, verbose_name='SQL de Custo')),
                ('equipment_observation', models.CharField(blank=True, db_column='CF_OBSERVACAO_EQP', max_length=8000, null=True, verbose_name='Observação do Equipamento')),
                ('utility_notes', models.CharField(blank=True, db_column='CF_UTILIDADE', max_length=1000, null=True, verbose_name='Utilidade')),
                ('usage_notes', models.CharField(blank=True, db_column='CF_UTILIZACAO', max_length=300, null=True, verbose_name='Utilização')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'F_EQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentCostHistory',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('month', models.CharField(blank=True, db_column='MES', max_length=2, null=True, verbose_name='Mês')),
                ('year', models.CharField(blank=True, db_column='ANO', max_length=4, null=True, verbose_name='Ano')),
                ('hourly_cost', models.DecimalField(blank=True, db_column='CUSTOHORA', decimal_places=4, max_digits=10, null=True, verbose_name='Custo Hora')),
                ('monthly_cost', models.DecimalField(blank=True, db_column='CUSTOMES', decimal_places=4, max_digits=10, null=True, verbose_name='Custo Mês')),
                ('is_current', models.IntegerField(blank=True, db_column='ATUAL', null=True, verbose_name='Atual')),
            ],
            options={
                'verbose_name': 'Histórico de Custo do Equipamento',
                'verbose_name_plural': 'Históricos de Custo dos Equipamentos',
                'db_table': 'F_HISTCUSTOEQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSkill',
            fields=[
                ('skill_quantity', models.IntegerField(blank=True, db_column='QTDHABILIDADE', null=True, verbose_name='Quantidade da Habilidade')),
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Habilidade do Equipamento',
                'verbose_name_plural': 'Habilidades dos Equipamentos',
                'db_table': 'F_EQUIPAMENTOHABILIDADES',
                'managed': False,
            },
        ),
    ]
