# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('branch_code', models.IntegerField(blank=True, db_column='CODFILIAL', null=True, verbose_name='Filial')),
                ('description', models.CharField(blank=True, db_column='DESCATIVIDADE', max_length=200, null=True, verbose_name='Descrição')),
                ('preparation', models.TextField(blank=True, db_column='PREPARACAO', null=True, verbose_name='Preparação')),
                ('execution', models.TextField(blank=True, db_column='EXECUCAO', null=True, verbose_name='Execução')),
                ('verification', models.TextField(blank=True, db_column='CONFERENCIA', null=True, verbose_name='Conferência')),
                ('activity_id', models.CharField(blank=True, db_column='IDATIVIDADE', max_length=30, null=True, verbose_name='ID da Atividade')),
                ('setup', models.IntegerField(blank=True, db_column='SETUP', null=True, verbose_name='Setup')),
                ('is_active', models.IntegerField(blank=True, db_column='ATIVO', null=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'F_ATIVIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityEquipment',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Equipamento da Atividade',
                'verbose_name_plural': 'Equipamentos da Atividade',
                'db_table': 'F_ATIVEQUIPAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySetup',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Setup de Atividade',
                'verbose_name_plural': 'Setups de Atividades',
                'db_table': 'F_ATIVIDADE_SETUP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySkills',
            fields=[
                ('amount_skills', models.IntegerField(blank=True, db_column='QTDHABILIDADE', null=True, verbose_name='Quantidade de Habilidade')),
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Habilidade da Atividade',
                'verbose_name_plural': 'Habilidades da Atividade',
                'db_table': 'F_ATIVHABILIDADES',
                'managed': False,
            },
        ),
    ]
