# Generated by Django 5.0.14 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopReason',
            fields=[
                ('code', models.AutoField(db_column='CODIGO', primary_key=True, serialize=False, verbose_name='Código')),
                ('stoppage_id', models.CharField(blank=True, db_column='IDPARADA', max_length=30, null=True, verbose_name='ID da Parada')),
                ('description', models.CharField(blank=True, db_column='DESCRICAOPARADA', max_length=200, null=True, verbose_name='Descrição da Parada')),
                ('is_active', models.IntegerField(blank=True, db_column='ATIVO', null=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Razão da Parada',
                'verbose_name_plural': 'Razões da Parada',
                'db_table': 'F_RAZOESPARADA',
                'managed': False,
            },
        ),
    ]
